keymap:
  - name: Helium Browser Remaps
    application:
      only: [helium]
    remap:
      C-j: C-PageUp
      C-semicolon: C-PageDown
      C-A-j: A-Left
      C-A-semicolon: A-Right

  - name: GNOME Papers Remaps
    application:
      only: [org.gnome.Papers]
    remap:
      C-j: Left
      C-k: Down
      C-l: Up
      C-semicolon: Right
